name: burgan_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations: # Localization support
    sdk: flutter
  json_serializable: ^6.8.0
  jwt_decode: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.0.20
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0 # For generating QR codes
  qr_code_scanner: ^0.6.1 # For scanning QR codes
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
